apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::038827976211:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1462EKO9J50L9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::038827976211:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-10T19:15:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4035"
  uid: ba6ca674-2590-421d-be45-c57fbac9b2f3
